[package]
name = "relabel"
version = "0.1.0"
edition = "2024"

[dependencies]
encrustant = { path = "../encrustant" }
rayon = "1.10.0"
clap = { version = "4.5.32", features = ["derive"] }

[profile.release]
lto = true
codegen-units = 1
